graph TD
    Newtonsoft.Json --> Microsoft.CSharp
    Newtonsoft.Json --> NETStandard.Library
    Newtonsoft.Json --> System.ComponentModel.TypeConverter
    Newtonsoft.Json --> System.Runtime.Serialization.Primitives
    Newtonsoft.Json --> Microsoft.CSharp
    Newtonsoft.Json --> NETStandard.Library
    Newtonsoft.Json --> System.ComponentModel.TypeConverter
    Newtonsoft.Json --> System.Runtime.Serialization.Formatters
    Newtonsoft.Json --> System.Runtime.Serialization.Primitives
    Newtonsoft.Json --> System.Xml.XmlDocument
    Microsoft.CSharp --> NETStandard.Library
    Microsoft.CSharp --> System.Dynamic.Runtime
    Microsoft.CSharp --> System.Reflection.TypeExtensions
    Microsoft.CSharp --> NETStandard.Library
    Microsoft.CSharp --> System.Dynamic.Runtime
    Microsoft.CSharp --> NETStandard.Library
    Microsoft.CSharp --> System.Dynamic.Runtime
    Microsoft.CSharp --> System.Reflection.TypeExtensions
    NETStandard.Library --> Microsoft.NETCore.Platforms
    NETStandard.Library --> System.Runtime.InteropServices.RuntimeInformation
    NETStandard.Library --> Microsoft.NETCore.Platforms
    NETStandard.Library --> Microsoft.Win32.Primitives
    NETStandard.Library --> System.AppContext
    NETStandard.Library --> System.Console
    NETStandard.Library --> System.Globalization.Calendars
    NETStandard.Library --> System.IO.Compression
    NETStandard.Library --> System.IO.Compression.ZipFile
    NETStandard.Library --> System.IO.FileSystem
    NETStandard.Library --> System.IO.FileSystem.Primitives
    NETStandard.Library --> System.Net.Http
    NETStandard.Library --> System.Net.Sockets
    NETStandard.Library --> System.Runtime.InteropServices.RuntimeInformation
    NETStandard.Library --> System.Security.Cryptography.Algorithms
    NETStandard.Library --> System.Security.Cryptography.Encoding
    NETStandard.Library --> System.Security.Cryptography.Primitives
    NETStandard.Library --> System.Security.Cryptography.X509Certificates
    NETStandard.Library --> System.Xml.ReaderWriter
    NETStandard.Library --> Microsoft.NETCore.Platforms
    NETStandard.Library --> Microsoft.NETCore.Platforms
    NETStandard.Library --> Microsoft.NETCore.Platforms
    NETStandard.Library --> System.Collections
    NETStandard.Library --> System.Diagnostics.Debug
    NETStandard.Library --> System.Diagnostics.Tools
    NETStandard.Library --> System.Globalization
    NETStandard.Library --> System.IO
    NETStandard.Library --> System.Linq
    NETStandard.Library --> System.Linq.Expressions
    NETStandard.Library --> System.Net.Primitives
    NETStandard.Library --> System.ObjectModel
    NETStandard.Library --> System.Reflection
    NETStandard.Library --> System.Reflection.Extensions
    NETStandard.Library --> System.Reflection.Primitives
    NETStandard.Library --> System.Resources.ResourceManager
    NETStandard.Library --> System.Runtime
    NETStandard.Library --> System.Runtime.Extensions
    NETStandard.Library --> System.Text.Encoding
    NETStandard.Library --> System.Text.Encoding.Extensions
    NETStandard.Library --> System.Text.RegularExpressions
    NETStandard.Library --> System.Threading
    NETStandard.Library --> System.Threading.Tasks
    NETStandard.Library --> System.Xml.ReaderWriter
    NETStandard.Library --> System.Xml.XDocument
    NETStandard.Library --> Microsoft.NETCore.Platforms
    NETStandard.Library --> System.Collections
    NETStandard.Library --> System.Collections.Concurrent
    NETStandard.Library --> System.Diagnostics.Debug
    NETStandard.Library --> System.Diagnostics.Tools
    NETStandard.Library --> System.Diagnostics.Tracing
    NETStandard.Library --> System.Globalization
    NETStandard.Library --> System.IO
    NETStandard.Library --> System.IO.Compression
    NETStandard.Library --> System.Linq
    NETStandard.Library --> System.Linq.Expressions
    NETStandard.Library --> System.Net.Http
    NETStandard.Library --> System.Net.Primitives
    NETStandard.Library --> System.ObjectModel
    NETStandard.Library --> System.Reflection
    NETStandard.Library --> System.Reflection.Extensions
    NETStandard.Library --> System.Reflection.Primitives
    NETStandard.Library --> System.Resources.ResourceManager
    NETStandard.Library --> System.Runtime
    NETStandard.Library --> System.Runtime.Extensions
    NETStandard.Library --> System.Runtime.InteropServices
    NETStandard.Library --> System.Runtime.InteropServices.RuntimeInformation
    NETStandard.Library --> System.Runtime.Numerics
    NETStandard.Library --> System.Text.Encoding
    NETStandard.Library --> System.Text.Encoding.Extensions
    NETStandard.Library --> System.Text.RegularExpressions
    NETStandard.Library --> System.Threading
    NETStandard.Library --> System.Threading.Tasks
    NETStandard.Library --> System.Xml.ReaderWriter
    NETStandard.Library --> System.Xml.XDocument
    NETStandard.Library --> Microsoft.NETCore.Platforms
    NETStandard.Library --> System.Collections
    NETStandard.Library --> System.Collections.Concurrent
    NETStandard.Library --> System.Diagnostics.Debug
    NETStandard.Library --> System.Diagnostics.Tools
    NETStandard.Library --> System.Diagnostics.Tracing
    NETStandard.Library --> System.Globalization
    NETStandard.Library --> System.IO
    NETStandard.Library --> System.IO.Compression
    NETStandard.Library --> System.Linq
    NETStandard.Library --> System.Linq.Expressions
    NETStandard.Library --> System.Net.Http
    NETStandard.Library --> System.Net.Primitives
    NETStandard.Library --> System.ObjectModel
    NETStandard.Library --> System.Reflection
    NETStandard.Library --> System.Reflection.Extensions
    NETStandard.Library --> System.Reflection.Primitives
    NETStandard.Library --> System.Resources.ResourceManager
    NETStandard.Library --> System.Runtime
    NETStandard.Library --> System.Runtime.Extensions
    NETStandard.Library --> System.Runtime.InteropServices
    NETStandard.Library --> System.Runtime.InteropServices.RuntimeInformation
    NETStandard.Library --> System.Runtime.Numerics
    NETStandard.Library --> System.Text.Encoding
    NETStandard.Library --> System.Text.Encoding.Extensions
    NETStandard.Library --> System.Text.RegularExpressions
    NETStandard.Library --> System.Threading
    NETStandard.Library --> System.Threading.Tasks
    NETStandard.Library --> System.Threading.Timer
    NETStandard.Library --> System.Xml.ReaderWriter
    NETStandard.Library --> System.Xml.XDocument
    NETStandard.Library --> Microsoft.NETCore.Platforms
    NETStandard.Library --> Microsoft.Win32.Primitives
    NETStandard.Library --> System.AppContext
    NETStandard.Library --> System.Collections
    NETStandard.Library --> System.Collections.Concurrent
    NETStandard.Library --> System.Console
    NETStandard.Library --> System.Diagnostics.Debug
    NETStandard.Library --> System.Diagnostics.Tools
    NETStandard.Library --> System.Diagnostics.Tracing
    NETStandard.Library --> System.Globalization
    NETStandard.Library --> System.Globalization.Calendars
    NETStandard.Library --> System.IO
    NETStandard.Library --> System.IO.Compression
    NETStandard.Library --> System.IO.Compression.ZipFile
    NETStandard.Library --> System.IO.FileSystem
    NETStandard.Library --> System.IO.FileSystem.Primitives
    NETStandard.Library --> System.Linq
    NETStandard.Library --> System.Linq.Expressions
    NETStandard.Library --> System.Net.Http
    NETStandard.Library --> System.Net.Primitives
    NETStandard.Library --> System.Net.Sockets
    NETStandard.Library --> System.ObjectModel
    NETStandard.Library --> System.Reflection
    NETStandard.Library --> System.Reflection.Extensions
    NETStandard.Library --> System.Reflection.Primitives
    NETStandard.Library --> System.Resources.ResourceManager
    NETStandard.Library --> System.Runtime
    NETStandard.Library --> System.Runtime.Extensions
    NETStandard.Library --> System.Runtime.Handles
    NETStandard.Library --> System.Runtime.InteropServices
    NETStandard.Library --> System.Runtime.InteropServices.RuntimeInformation
    NETStandard.Library --> System.Runtime.Numerics
    NETStandard.Library --> System.Security.Cryptography.Algorithms
    NETStandard.Library --> System.Security.Cryptography.Encoding
    NETStandard.Library --> System.Security.Cryptography.Primitives
    NETStandard.Library --> System.Security.Cryptography.X509Certificates
    NETStandard.Library --> System.Text.Encoding
    NETStandard.Library --> System.Text.Encoding.Extensions
    NETStandard.Library --> System.Text.RegularExpressions
    NETStandard.Library --> System.Threading
    NETStandard.Library --> System.Threading.Tasks
    NETStandard.Library --> System.Threading.Timer
    NETStandard.Library --> System.Xml.ReaderWriter
    NETStandard.Library --> System.Xml.XDocument
    NETStandard.Library --> Microsoft.NETCore.Platforms
    NETStandard.Library --> Microsoft.Win32.Primitives
    NETStandard.Library --> System.AppContext
    NETStandard.Library --> System.Collections
    NETStandard.Library --> System.Collections.Concurrent
    NETStandard.Library --> System.Console
    NETStandard.Library --> System.Diagnostics.Debug
    NETStandard.Library --> System.Diagnostics.Tools
    NETStandard.Library --> System.Diagnostics.Tracing
    NETStandard.Library --> System.Globalization
    NETStandard.Library --> System.Globalization.Calendars
    NETStandard.Library --> System.IO
    NETStandard.Library --> System.IO.Compression
    NETStandard.Library --> System.IO.Compression.ZipFile
    NETStandard.Library --> System.IO.FileSystem
    NETStandard.Library --> System.IO.FileSystem.Primitives
    NETStandard.Library --> System.Linq
    NETStandard.Library --> System.Linq.Expressions
    NETStandard.Library --> System.Net.Http
    NETStandard.Library --> System.Net.Primitives
    NETStandard.Library --> System.Net.Sockets
    NETStandard.Library --> System.ObjectModel
    NETStandard.Library --> System.Reflection
    NETStandard.Library --> System.Reflection.Extensions
    NETStandard.Library --> System.Reflection.Primitives
    NETStandard.Library --> System.Resources.ResourceManager
    NETStandard.Library --> System.Runtime
    NETStandard.Library --> System.Runtime.Extensions
    NETStandard.Library --> System.Runtime.Handles
    NETStandard.Library --> System.Runtime.InteropServices
    NETStandard.Library --> System.Runtime.InteropServices.RuntimeInformation
    NETStandard.Library --> System.Runtime.Numerics
    NETStandard.Library --> System.Security.Cryptography.Algorithms
    NETStandard.Library --> System.Security.Cryptography.Encoding
    NETStandard.Library --> System.Security.Cryptography.Primitives
    NETStandard.Library --> System.Security.Cryptography.X509Certificates
    NETStandard.Library --> System.Text.Encoding
    NETStandard.Library --> System.Text.Encoding.Extensions
    NETStandard.Library --> System.Text.RegularExpressions
    NETStandard.Library --> System.Threading
    NETStandard.Library --> System.Threading.Tasks
    NETStandard.Library --> System.Threading.Timer
    NETStandard.Library --> System.Xml.ReaderWriter
    NETStandard.Library --> System.Xml.XDocument
    NETStandard.Library --> Microsoft.NETCore.Platforms
    NETStandard.Library --> Microsoft.Win32.Primitives
    NETStandard.Library --> System.AppContext
    NETStandard.Library --> System.Collections
    NETStandard.Library --> System.Collections.Concurrent
    NETStandard.Library --> System.Console
    NETStandard.Library --> System.Diagnostics.Debug
    NETStandard.Library --> System.Diagnostics.Tools
    NETStandard.Library --> System.Diagnostics.Tracing
    NETStandard.Library --> System.Globalization
    NETStandard.Library --> System.Globalization.Calendars
    NETStandard.Library --> System.IO
    NETStandard.Library --> System.IO.Compression
    NETStandard.Library --> System.IO.Compression.ZipFile
    NETStandard.Library --> System.IO.FileSystem
    NETStandard.Library --> System.IO.FileSystem.Primitives
    NETStandard.Library --> System.Linq
    NETStandard.Library --> System.Linq.Expressions
    NETStandard.Library --> System.Net.Http
    NETStandard.Library --> System.Net.Primitives
    NETStandard.Library --> System.Net.Sockets
    NETStandard.Library --> System.ObjectModel
    NETStandard.Library --> System.Reflection
    NETStandard.Library --> System.Reflection.Extensions
    NETStandard.Library --> System.Reflection.Primitives
    NETStandard.Library --> System.Resources.ResourceManager
    NETStandard.Library --> System.Runtime
    NETStandard.Library --> System.Runtime.Extensions
    NETStandard.Library --> System.Runtime.Handles
    NETStandard.Library --> System.Runtime.InteropServices
    NETStandard.Library --> System.Runtime.InteropServices.RuntimeInformation
    NETStandard.Library --> System.Runtime.Numerics
    NETStandard.Library --> System.Security.Cryptography.Algorithms
    NETStandard.Library --> System.Security.Cryptography.Encoding
    NETStandard.Library --> System.Security.Cryptography.Primitives
    NETStandard.Library --> System.Security.Cryptography.X509Certificates
    NETStandard.Library --> System.Text.Encoding
    NETStandard.Library --> System.Text.Encoding.Extensions
    NETStandard.Library --> System.Text.RegularExpressions
    NETStandard.Library --> System.Threading
    NETStandard.Library --> System.Threading.Tasks
    NETStandard.Library --> System.Threading.Timer
    NETStandard.Library --> System.Xml.ReaderWriter
    NETStandard.Library --> System.Xml.XDocument
    NETStandard.Library --> Microsoft.NETCore.Platforms
    NETStandard.Library --> Microsoft.Win32.Primitives
    NETStandard.Library --> System.AppContext
    NETStandard.Library --> System.Collections
    NETStandard.Library --> System.Collections.Concurrent
    NETStandard.Library --> System.Console
    NETStandard.Library --> System.Diagnostics.Debug
    NETStandard.Library --> System.Diagnostics.Tools
    NETStandard.Library --> System.Diagnostics.Tracing
    NETStandard.Library --> System.Globalization
    NETStandard.Library --> System.Globalization.Calendars
    NETStandard.Library --> System.IO
    NETStandard.Library --> System.IO.Compression
    NETStandard.Library --> System.IO.Compression.ZipFile
    NETStandard.Library --> System.IO.FileSystem
    NETStandard.Library --> System.IO.FileSystem.Primitives
    NETStandard.Library --> System.Linq
    NETStandard.Library --> System.Linq.Expressions
    NETStandard.Library --> System.Net.Http
    NETStandard.Library --> System.Net.Primitives
    NETStandard.Library --> System.Net.Sockets
    NETStandard.Library --> System.ObjectModel
    NETStandard.Library --> System.Reflection
    NETStandard.Library --> System.Reflection.Extensions
    NETStandard.Library --> System.Reflection.Primitives
    NETStandard.Library --> System.Resources.ResourceManager
    NETStandard.Library --> System.Runtime
    NETStandard.Library --> System.Runtime.Extensions
    NETStandard.Library --> System.Runtime.Handles
    NETStandard.Library --> System.Runtime.InteropServices
    NETStandard.Library --> System.Runtime.InteropServices.RuntimeInformation
    NETStandard.Library --> System.Runtime.Numerics
    NETStandard.Library --> System.Security.Cryptography.Algorithms
    NETStandard.Library --> System.Security.Cryptography.Encoding
    NETStandard.Library --> System.Security.Cryptography.Primitives
    NETStandard.Library --> System.Security.Cryptography.X509Certificates
    NETStandard.Library --> System.Text.Encoding
    NETStandard.Library --> System.Text.Encoding.Extensions
    NETStandard.Library --> System.Text.RegularExpressions
    NETStandard.Library --> System.Threading
    NETStandard.Library --> System.Threading.Tasks
    NETStandard.Library --> System.Threading.Timer
    NETStandard.Library --> System.Xml.ReaderWriter
    NETStandard.Library --> System.Xml.XDocument
    NETStandard.Library --> Microsoft.NETCore.Platforms
    NETStandard.Library --> Microsoft.NETCore.Platforms
    NETStandard.Library --> System.Runtime.InteropServices.RuntimeInformation
    NETStandard.Library --> Microsoft.NETCore.Platforms
    NETStandard.Library --> Microsoft.NETCore.Platforms
    NETStandard.Library --> System.Runtime.InteropServices.RuntimeInformation
    NETStandard.Library --> Microsoft.NETCore.Platforms
    NETStandard.Library --> Microsoft.Win32.Primitives
    NETStandard.Library --> System.AppContext
    NETStandard.Library --> System.Collections
    NETStandard.Library --> System.Collections.Concurrent
    NETStandard.Library --> System.Console
    NETStandard.Library --> System.Diagnostics.Debug
    NETStandard.Library --> System.Diagnostics.Tools
    NETStandard.Library --> System.Diagnostics.Tracing
    NETStandard.Library --> System.Globalization
    NETStandard.Library --> System.Globalization.Calendars
    NETStandard.Library --> System.IO
    NETStandard.Library --> System.IO.Compression
    NETStandard.Library --> System.IO.Compression.ZipFile
    NETStandard.Library --> System.IO.FileSystem
    NETStandard.Library --> System.IO.FileSystem.Primitives
    NETStandard.Library --> System.Linq
    NETStandard.Library --> System.Linq.Expressions
    NETStandard.Library --> System.Net.Http
    NETStandard.Library --> System.Net.Primitives
    NETStandard.Library --> System.Net.Sockets
    NETStandard.Library --> System.ObjectModel
    NETStandard.Library --> System.Reflection
    NETStandard.Library --> System.Reflection.Extensions
    NETStandard.Library --> System.Reflection.Primitives
    NETStandard.Library --> System.Resources.ResourceManager
    NETStandard.Library --> System.Runtime
    NETStandard.Library --> System.Runtime.Extensions
    NETStandard.Library --> System.Runtime.Handles
    NETStandard.Library --> System.Runtime.InteropServices
    NETStandard.Library --> System.Runtime.InteropServices.RuntimeInformation
    NETStandard.Library --> System.Runtime.Numerics
    NETStandard.Library --> System.Security.Cryptography.Algorithms
    NETStandard.Library --> System.Security.Cryptography.Encoding
    NETStandard.Library --> System.Security.Cryptography.Primitives
    NETStandard.Library --> System.Security.Cryptography.X509Certificates
    NETStandard.Library --> System.Text.Encoding
    NETStandard.Library --> System.Text.Encoding.Extensions
    NETStandard.Library --> System.Text.RegularExpressions
    NETStandard.Library --> System.Threading
    NETStandard.Library --> System.Threading.Tasks
    NETStandard.Library --> System.Threading.Timer
    NETStandard.Library --> System.Xml.ReaderWriter
    NETStandard.Library --> System.Xml.XDocument
    NETStandard.Library --> Microsoft.NETCore.Platforms
    NETStandard.Library --> Microsoft.NETCore.Platforms
    NETStandard.Library --> System.Runtime.InteropServices.RuntimeInformation
    NETStandard.Library --> Microsoft.NETCore.Platforms
    NETStandard.Library --> Microsoft.NETCore.Platforms
    NETStandard.Library --> System.Runtime.InteropServices.RuntimeInformation
    System.Dynamic.Runtime --> System.Collections
    System.Dynamic.Runtime --> System.Diagnostics.Debug
    System.Dynamic.Runtime --> System.Globalization
    System.Dynamic.Runtime --> System.Linq
    System.Dynamic.Runtime --> System.Linq.Expressions
    System.Dynamic.Runtime --> System.ObjectModel
    System.Dynamic.Runtime --> System.Reflection
    System.Dynamic.Runtime --> System.Reflection.TypeExtensions
    System.Dynamic.Runtime --> System.Resources.ResourceManager
    System.Dynamic.Runtime --> System.Runtime
    System.Dynamic.Runtime --> System.Runtime.Extensions
    System.Dynamic.Runtime --> System.Threading
    System.Dynamic.Runtime --> System.Linq.Expressions
    System.Dynamic.Runtime --> System.ObjectModel
    System.Dynamic.Runtime --> System.Reflection
    System.Dynamic.Runtime --> System.Runtime
    System.Dynamic.Runtime --> System.Collections
    System.Dynamic.Runtime --> System.Diagnostics.Debug
    System.Dynamic.Runtime --> System.Linq
    System.Dynamic.Runtime --> System.Linq.Expressions
    System.Dynamic.Runtime --> System.ObjectModel
    System.Dynamic.Runtime --> System.Reflection
    System.Dynamic.Runtime --> System.Reflection.Emit
    System.Dynamic.Runtime --> System.Reflection.Emit.ILGeneration
    System.Dynamic.Runtime --> System.Reflection.Primitives
    System.Dynamic.Runtime --> System.Reflection.TypeExtensions
    System.Dynamic.Runtime --> System.Resources.ResourceManager
    System.Dynamic.Runtime --> System.Runtime
    System.Dynamic.Runtime --> System.Runtime.Extensions
    System.Dynamic.Runtime --> System.Threading
    System.Reflection.TypeExtensions --> System.Diagnostics.Contracts
    System.Reflection.TypeExtensions --> System.Diagnostics.Debug
    System.Reflection.TypeExtensions --> System.Linq
    System.Reflection.TypeExtensions --> System.Reflection
    System.Reflection.TypeExtensions --> System.Reflection.Primitives
    System.Reflection.TypeExtensions --> System.Resources.ResourceManager
    System.Reflection.TypeExtensions --> System.Runtime
    System.Reflection.TypeExtensions --> System.Runtime.Extensions
    System.Reflection.TypeExtensions --> System.Reflection
    System.Reflection.TypeExtensions --> System.Resources.ResourceManager
    System.Reflection.TypeExtensions --> System.Runtime
    System.Reflection.TypeExtensions --> System.Reflection
    System.Reflection.TypeExtensions --> System.Resources.ResourceManager
    System.Reflection.TypeExtensions --> System.Runtime
    System.ComponentModel.TypeConverter --> System.ComponentModel.Primitives
    System.ComponentModel.TypeConverter --> System.Collections.NonGeneric
    System.ComponentModel.TypeConverter --> System.ComponentModel.Primitives
    System.ComponentModel.TypeConverter --> System.Collections
    System.ComponentModel.TypeConverter --> System.ComponentModel
    System.ComponentModel.TypeConverter --> System.ComponentModel.Primitives
    System.ComponentModel.TypeConverter --> System.Globalization
    System.ComponentModel.TypeConverter --> System.Reflection
    System.ComponentModel.TypeConverter --> System.Reflection.Extensions
    System.ComponentModel.TypeConverter --> System.Reflection.Primitives
    System.ComponentModel.TypeConverter --> System.Resources.ResourceManager
    System.ComponentModel.TypeConverter --> System.Runtime
    System.ComponentModel.TypeConverter --> System.Runtime.Extensions
    System.ComponentModel.TypeConverter --> System.Threading
    System.ComponentModel.TypeConverter --> System.Collections
    System.ComponentModel.TypeConverter --> System.Collections.NonGeneric
    System.ComponentModel.TypeConverter --> System.Collections.Specialized
    System.ComponentModel.TypeConverter --> System.ComponentModel
    System.ComponentModel.TypeConverter --> System.ComponentModel.Primitives
    System.ComponentModel.TypeConverter --> System.Globalization
    System.ComponentModel.TypeConverter --> System.Linq
    System.ComponentModel.TypeConverter --> System.Reflection
    System.ComponentModel.TypeConverter --> System.Reflection.Extensions
    System.ComponentModel.TypeConverter --> System.Reflection.Primitives
    System.ComponentModel.TypeConverter --> System.Reflection.TypeExtensions
    System.ComponentModel.TypeConverter --> System.Resources.ResourceManager
    System.ComponentModel.TypeConverter --> System.Runtime
    System.ComponentModel.TypeConverter --> System.Runtime.Extensions
    System.ComponentModel.TypeConverter --> System.Threading
    System.ComponentModel.TypeConverter --> System.ComponentModel.Primitives
    System.ComponentModel.TypeConverter --> System.ComponentModel.Primitives
    System.ComponentModel.TypeConverter --> System.ComponentModel.Primitives
    System.ComponentModel.Primitives --> System.ComponentModel
    System.ComponentModel.Primitives --> System.Resources.ResourceManager
    System.ComponentModel.Primitives --> System.Runtime
    System.Collections.NonGeneric --> System.Diagnostics.Debug
    System.Collections.NonGeneric --> System.Globalization
    System.Collections.NonGeneric --> System.Resources.ResourceManager
    System.Collections.NonGeneric --> System.Runtime
    System.Collections.NonGeneric --> System.Runtime.Extensions
    System.Collections.NonGeneric --> System.Threading
    System.Collections --> Microsoft.NETCore.Platforms
    System.Collections --> Microsoft.NETCore.Targets
    System.Collections --> System.Runtime
    System.Collections --> Microsoft.NETCore.Platforms
    System.Collections --> Microsoft.NETCore.Targets
    System.Collections --> System.Runtime
    System.Collections --> Microsoft.NETCore.Platforms
    System.Collections --> Microsoft.NETCore.Targets
    System.Collections --> System.Runtime
    System.ComponentModel --> System.Runtime
    System.ComponentModel --> System.Runtime
    System.ComponentModel --> System.Runtime
    System.Globalization --> Microsoft.NETCore.Platforms
    System.Globalization --> Microsoft.NETCore.Targets
    System.Globalization --> System.Runtime
    System.Globalization --> Microsoft.NETCore.Platforms
    System.Globalization --> Microsoft.NETCore.Targets
    System.Globalization --> System.Runtime
    System.Globalization --> Microsoft.NETCore.Platforms
    System.Globalization --> Microsoft.NETCore.Targets
    System.Globalization --> System.Runtime
    System.Reflection --> Microsoft.NETCore.Platforms
    System.Reflection --> Microsoft.NETCore.Targets
    System.Reflection --> System.IO
    System.Reflection --> System.Reflection.Primitives
    System.Reflection --> System.Runtime
    System.Reflection --> Microsoft.NETCore.Platforms
    System.Reflection --> Microsoft.NETCore.Targets
    System.Reflection --> System.IO
    System.Reflection --> System.Reflection.Primitives
    System.Reflection --> System.Runtime
    System.Reflection --> Microsoft.NETCore.Platforms
    System.Reflection --> Microsoft.NETCore.Targets
    System.Reflection --> System.IO
    System.Reflection --> System.Reflection.Primitives
    System.Reflection --> System.Runtime
    System.Reflection --> Microsoft.NETCore.Platforms
    System.Reflection --> Microsoft.NETCore.Targets
    System.Reflection --> System.IO
    System.Reflection --> System.Reflection.Primitives
    System.Reflection --> System.Runtime
    System.Reflection.Extensions --> Microsoft.NETCore.Platforms
    System.Reflection.Extensions --> Microsoft.NETCore.Targets
    System.Reflection.Extensions --> System.Reflection
    System.Reflection.Extensions --> System.Runtime
    System.Reflection.Extensions --> Microsoft.NETCore.Platforms
    System.Reflection.Extensions --> Microsoft.NETCore.Targets
    System.Reflection.Extensions --> System.Reflection
    System.Reflection.Extensions --> System.Runtime
    System.Reflection.Primitives --> Microsoft.NETCore.Platforms
    System.Reflection.Primitives --> Microsoft.NETCore.Targets
    System.Reflection.Primitives --> System.Runtime
    System.Reflection.Primitives --> Microsoft.NETCore.Platforms
    System.Reflection.Primitives --> Microsoft.NETCore.Targets
    System.Reflection.Primitives --> System.Runtime
    System.Resources.ResourceManager --> Microsoft.NETCore.Platforms
    System.Resources.ResourceManager --> Microsoft.NETCore.Targets
    System.Resources.ResourceManager --> System.Globalization
    System.Resources.ResourceManager --> System.Reflection
    System.Resources.ResourceManager --> System.Runtime
    System.Resources.ResourceManager --> Microsoft.NETCore.Platforms
    System.Resources.ResourceManager --> Microsoft.NETCore.Targets
    System.Resources.ResourceManager --> System.Globalization
    System.Resources.ResourceManager --> System.Reflection
    System.Resources.ResourceManager --> System.Runtime
    System.Runtime --> Microsoft.NETCore.Platforms
    System.Runtime --> Microsoft.NETCore.Targets
    System.Runtime --> Microsoft.NETCore.Platforms
    System.Runtime --> Microsoft.NETCore.Targets
    System.Runtime --> Microsoft.NETCore.Platforms
    System.Runtime --> Microsoft.NETCore.Targets
    System.Runtime --> Microsoft.NETCore.Platforms
    System.Runtime --> Microsoft.NETCore.Targets
    System.Runtime --> Microsoft.NETCore.Platforms
    System.Runtime --> Microsoft.NETCore.Targets
    System.Runtime.Extensions --> Microsoft.NETCore.Platforms
    System.Runtime.Extensions --> Microsoft.NETCore.Targets
    System.Runtime.Extensions --> System.Runtime
    System.Runtime.Extensions --> Microsoft.NETCore.Platforms
    System.Runtime.Extensions --> Microsoft.NETCore.Targets
    System.Runtime.Extensions --> System.Runtime
    System.Runtime.Extensions --> Microsoft.NETCore.Platforms
    System.Runtime.Extensions --> Microsoft.NETCore.Targets
    System.Runtime.Extensions --> System.Runtime
    System.Runtime.Extensions --> Microsoft.NETCore.Platforms
    System.Runtime.Extensions --> Microsoft.NETCore.Targets
    System.Runtime.Extensions --> System.Runtime
    System.Threading --> System.Runtime
    System.Threading --> System.Threading.Tasks
    System.Threading --> System.Runtime
    System.Threading --> System.Threading.Tasks
    System.Threading --> System.Runtime
    System.Threading --> System.Threading.Tasks
    System.Collections.Specialized --> System.Collections.NonGeneric
    System.Collections.Specialized --> System.Globalization
    System.Collections.Specialized --> System.Globalization.Extensions
    System.Collections.Specialized --> System.Resources.ResourceManager
    System.Collections.Specialized --> System.Runtime
    System.Collections.Specialized --> System.Runtime.Extensions
    System.Collections.Specialized --> System.Threading
    System.Linq --> System.Collections
    System.Linq --> System.Diagnostics.Debug
    System.Linq --> System.Resources.ResourceManager
    System.Linq --> System.Runtime
    System.Linq --> System.Runtime.Extensions
    System.Linq --> System.Collections
    System.Linq --> System.Runtime
    System.Linq --> System.Collections
    System.Linq --> System.Diagnostics.Debug
    System.Linq --> System.Resources.ResourceManager
    System.Linq --> System.Runtime
    System.Linq --> System.Runtime.Extensions
    System.Runtime.Serialization.Primitives --> System.Resources.ResourceManager
    System.Runtime.Serialization.Primitives --> System.Runtime
    System.Runtime.Serialization.Primitives --> System.Runtime
    System.Runtime.Serialization.Primitives --> System.Resources.ResourceManager
    System.Runtime.Serialization.Primitives --> System.Runtime
    System.Runtime.Serialization.Formatters
    System.Xml.XmlDocument --> System.Collections
    System.Xml.XmlDocument --> System.Diagnostics.Debug
    System.Xml.XmlDocument --> System.Globalization
    System.Xml.XmlDocument --> System.IO
    System.Xml.XmlDocument --> System.Resources.ResourceManager
    System.Xml.XmlDocument --> System.Runtime
    System.Xml.XmlDocument --> System.Runtime.Extensions
    System.Xml.XmlDocument --> System.Text.Encoding
    System.Xml.XmlDocument --> System.Threading
    System.Xml.XmlDocument --> System.Xml.ReaderWriter
    System.Diagnostics.Debug --> Microsoft.NETCore.Platforms
    System.Diagnostics.Debug --> Microsoft.NETCore.Targets
    System.Diagnostics.Debug --> System.Runtime
    System.Diagnostics.Debug --> Microsoft.NETCore.Platforms
    System.Diagnostics.Debug --> Microsoft.NETCore.Targets
    System.Diagnostics.Debug --> System.Runtime
    System.Diagnostics.Debug --> Microsoft.NETCore.Platforms
    System.Diagnostics.Debug --> Microsoft.NETCore.Targets
    System.Diagnostics.Debug --> System.Runtime
    System.IO --> Microsoft.NETCore.Platforms
    System.IO --> Microsoft.NETCore.Targets
    System.IO --> System.Runtime
    System.IO --> System.Text.Encoding
    System.IO --> System.Threading.Tasks
    System.IO --> Microsoft.NETCore.Platforms
    System.IO --> Microsoft.NETCore.Targets
    System.IO --> System.Runtime
    System.IO --> System.Text.Encoding
    System.IO --> System.Threading.Tasks
    System.IO --> Microsoft.NETCore.Platforms
    System.IO --> Microsoft.NETCore.Targets
    System.IO --> System.Runtime
    System.IO --> System.Text.Encoding
    System.IO --> System.Threading.Tasks
    System.IO --> Microsoft.NETCore.Platforms
    System.IO --> Microsoft.NETCore.Targets
    System.IO --> System.Runtime
    System.IO --> System.Text.Encoding
    System.IO --> System.Threading.Tasks
    System.Text.Encoding --> Microsoft.NETCore.Platforms
    System.Text.Encoding --> Microsoft.NETCore.Targets
    System.Text.Encoding --> System.Runtime
    System.Text.Encoding --> Microsoft.NETCore.Platforms
    System.Text.Encoding --> Microsoft.NETCore.Targets
    System.Text.Encoding --> System.Runtime
    System.Text.Encoding --> Microsoft.NETCore.Platforms
    System.Text.Encoding --> Microsoft.NETCore.Targets
    System.Text.Encoding --> System.Runtime
    System.Xml.ReaderWriter --> System.Collections
    System.Xml.ReaderWriter --> System.Diagnostics.Debug
    System.Xml.ReaderWriter --> System.Globalization
    System.Xml.ReaderWriter --> System.IO
    System.Xml.ReaderWriter --> System.IO.FileSystem
    System.Xml.ReaderWriter --> System.IO.FileSystem.Primitives
    System.Xml.ReaderWriter --> System.Resources.ResourceManager
    System.Xml.ReaderWriter --> System.Runtime
    System.Xml.ReaderWriter --> System.Runtime.Extensions
    System.Xml.ReaderWriter --> System.Runtime.InteropServices
    System.Xml.ReaderWriter --> System.Text.Encoding
    System.Xml.ReaderWriter --> System.Text.Encoding.Extensions
    System.Xml.ReaderWriter --> System.Text.RegularExpressions
    System.Xml.ReaderWriter --> System.Threading.Tasks
    System.Xml.ReaderWriter --> System.Threading.Tasks.Extensions
    System.Xml.ReaderWriter --> System.IO
    System.Xml.ReaderWriter --> System.Runtime
    System.Xml.ReaderWriter --> System.Text.Encoding
    System.Xml.ReaderWriter --> System.Threading.Tasks
    System.Xml.ReaderWriter --> System.Collections
    System.Xml.ReaderWriter --> System.Diagnostics.Debug
    System.Xml.ReaderWriter --> System.Globalization
    System.Xml.ReaderWriter --> System.IO
    System.Xml.ReaderWriter --> System.IO.FileSystem
    System.Xml.ReaderWriter --> System.IO.FileSystem.Primitives
    System.Xml.ReaderWriter --> System.Resources.ResourceManager
    System.Xml.ReaderWriter --> System.Runtime
    System.Xml.ReaderWriter --> System.Runtime.Extensions
    System.Xml.ReaderWriter --> System.Runtime.InteropServices
    System.Xml.ReaderWriter --> System.Text.Encoding
    System.Xml.ReaderWriter --> System.Text.Encoding.Extensions
    System.Xml.ReaderWriter --> System.Text.RegularExpressions
    System.Xml.ReaderWriter --> System.Threading.Tasks
    System.Xml.ReaderWriter --> System.Threading.Tasks.Extensions