screen_width = 1920
screen_height = 1080
key_bindings = [ "w", "a", "s", "d", "space", "shift",]

[struct]
sound_volume = 80
music_volume = 60
effects_volume = 100

[struct1]
vsync = 1
antialiasing = 4
shadows = "high"
textures = "ultra"
