port = 8080
timeout = 30
max_connections = 100
server_name = "example.com"
array = [ "192.168.1.1", "192.168.1.2", "192.168.1.3",]
new_port = 8081
new_timeout = 25
new_max_connections = 200
min_value = 30
max_value = 8080

[table]
ip = "\"192.168.1.1\","
mask = "\"255.255.255.0\","
gateway = "192.168.1.254"
